import CostClassification from "./costClassification";
import {ICompany} from "@coreModule/database/schemas/company/company";
import {getLogger, serverLogger} from "@coreModule/loggers/serverLog";
import {ebkpHSeed} from "@propertyManagement/database/seeds/costClassification/ebkpH.seed";
import {bkpSeed} from "@propertyManagement/database/seeds/costClassification/bkp.seed";
import {npkSeed} from "@propertyManagement/database/seeds/costClassification/npk.seed";
import {siaSeed} from "@propertyManagement/database/seeds/costClassification/sia.seed";

const allSeeds = [...ebkpHSeed, ...bkpSeed, ...npkSeed, ...siaSeed];

/**
 * Seeds the Swiss cost-standard reference tables (eBKP-H / BKP / NPK / SIA) for a company.
 * Idempotent: keyed on (company, standard, code); updates titles on re-run without
 * duplicating rows. Full CRB/SIA catalogues are licensed — these are skeletons.
 */
export async function createCostClassifications(parentLogger: serverLogger, company: ICompany) {
    const logger = getLogger("mongoDbInitialization-createCostClassifications", parentLogger);
    logger.start("Creating cost classifications (eBKP-H / BKP / NPK / SIA)...");

    let created = 0;
    for (const row of allSeeds) {
        try {
            const result = await CostClassification.updateOne(
                {company: company._id, standard: row.standard, code: row.code},
                {
                    $set: {
                        parentCode: row.parentCode,
                        level: row.level,
                        title: row.title,
                        unitOfMeasure: row.unitOfMeasure,
                        sortIndex: row.sortIndex,
                        active: true,
                    },
                    $setOnInsert: {
                        // name is normally auto-generated by the pre('validate') hook, which
                        // does not run on upsert — set a deterministic, unique value here.
                        name: `CC-${row.standard}-${String(row.code).replace(/\s+/g, "").toUpperCase()}`,
                        company: company._id,
                        createdBy: company.createdBy,
                    },
                },
                {upsert: true},
            );
            if (result.upsertedCount > 0) created += 1;
        } catch (e: any) {
            logger.err(`Error seeding cost classification ${row.standard}/${row.code}: ${e.message}`);
        }
    }

    logger.finish(`Finished creating cost classifications! (${created} new of ${allSeeds.length})`);
}
