import {ObjectId} from "mongodb";
import Snag from "./snag";
import {getLogger, serverLogger} from "@coreModule/loggers/serverLog";
import {ICompany} from "@coreModule/database/schemas/company/company";
import {snagsSeed} from "@propertyManagement/database/seeds/operations/snags.seed";
import {
    opt,
    optDate,
    resolveUser,
    type OperationsRefs,
} from "@propertyManagement/database/seeds/operations/operationsRefs";

export {snagsSeed as defaultSnags};

/**
 * Seeds handover snags. `name` (SNAG-…) is auto-generated by the schema and was not
 * exported, so idempotency keys on the preserved `_id`.
 */
export async function createSnags(
    parentLogger: serverLogger,
    company: ICompany,
    refs: OperationsRefs,
    unitIds: Map<string, ObjectId>,
): Promise<Map<string, ObjectId>> {
    const logger = getLogger("mongoDbInitialization-createSnags", parentLogger);
    logger.start(`Creating snags (${snagsSeed.length})...`);

    const created = new Map<string, ObjectId>();

    for (const row of snagsSeed) {
        try {
            const unit = unitIds.get(row.unit);
            if (!unit) {
                logger.warn(`Skipping snag ${row.id}: its unit was not seeded.`);
                continue;
            }

            const snagId = new ObjectId(row.id);
            const payload = {
                unit,
                title: row.title,
                description: row.description,
                location: row.location,
                status: row.status,
                severity: row.severity,
                ...opt("reportedBy", resolveUser(refs, row.reportedBy)),
                ...opt("assignedTo", resolveUser(refs, row.assignedTo)),
                dueDate: new Date(row.dueDate),
                ...optDate("resolvedAt", row.resolvedAt),
                photos: [],
                notes: row.notes,
                company: company._id,
                createdBy: company.createdBy,
            };

            const existing = await Snag.findById(snagId);
            if (existing) {
                existing.set(payload);
                await existing.save();
            } else {
                await Snag.create({_id: snagId, ...payload});
            }

            created.set(row.id, snagId);
        } catch (e: unknown) {
            const message = e instanceof Error ? e.message : String(e);
            console.log(e);
            logger.err(`Error creating snag ${row.id}: ${message}`);
        }
    }

    logger.finish("Finished creating snags!", created.size);
    return created;
}
