/**
 * Property management demo projects.
 *
 * GENERATED by `yarn export:property-hierarchy` — edit the exporter, not this file,
 * unless you are deliberately curating the shipped defaults.
 */
import type {ProjectSeedRow} from "./types";

export const projectsSeed: readonly ProjectSeedRow[] = [
    {
        "id": "6a50368bd2892db79d54cd54",
        "name": "Garda",
        "description": "Garda Tower në Tiranë do të jetë një ndërtesë ikonike me 33 kate, ku një ekzoskelet mbajtës me teksturë minerale ndërthuret në mënyrë harmonike me një volum elegant prej xhami të lakuar, duke krijuar një identitet arkitektonik modern dhe unik.\n\nKy koncept inovativ kombinon estetikën bashkëkohore me inxhinierinë e avancuar, duke e shndërruar Garda Tower në një nga projektet më të spikatura të panoramës urbane të Tiranës.",
        "saleCommissionRatePercent": "4",
        "reservationCommissionRatePercent": "2",
        "featuredOnHomepage": true,
        "featuredSortOrder": 0,
        "socialLinks": [
            {
                "name": "123",
                "link": "https://asdasd.com"
            }
        ],
        "mainImageId": "6a50370bd2892db79d54d9fe"
    },
    {
        "id": "6a7c47d1aed7415e48c8fce4",
        "name": "Dyeus",
        "description": "Dyeus",
        "featuredOnHomepage": false,
        "featuredSortOrder": 0,
        "magazineTitle": "Ttile 123123",
        "magazineDescription": "lsdakj lasdlkfj asldjflaskdf jlksadj",
        "socialLinks": [
            {
                "name": "123",
                "link": "https://123123123.com"
            }
        ],
        "mainImageId": "6a7c47d1aed7415e48c8fcd6"
    },
    {
        "id": "6a4f94ae99511ee1e0efb78a",
        "name": "Aria Residence",
        "description": "Aria Residence, Dhërmi – Standardi i Ri i Jetesës në Rivierën Shqiptare\n\nNëse kërkoni një pronë që kombinon privatësinë, luksin dhe arkitekturën moderne, Aria Residence në Dhërmi është zgjedhja ideale. Një projekt rezidencial ekskluziv, i vendosur në një nga zonat më të kërkuara të Rivierës Shqiptare, ku qetësia, natyra dhe afërsia me detin krijojnë një stil jetese të pakrahasueshëm.\n\nArkitekturë Bashkëkohore & Cilësi Europiane\nÇdo detaj është projektuar sipas standardeve më të larta të ndërtimit. Kombinimi i gurit natyral, xhamit panoramik dhe materialeve premium krijon një estetikë moderne, ndërsa izolimi termik dhe akustik garanton rehati maksimale gjatë gjithë vitit.\n\nPamje Panoramike drejt Detit Jon\nApartamenti ofron një panoramë të hapur dhe të përhershme mbi detin Jon, duke përfituar ndriçim natyral gjatë gjithë ditës dhe perëndime spektakolare që e bëjnë çdo moment të veçantë.\n\nPrivatësi, Siguri & Komoditet\nKompleksi është i mbyllur, i mirëadministruar dhe i konceptuar për banorë që vlerësojnë privatësinë, sigurinë dhe një ambient rezidencial të qetë e ekskluziv.\n\nNjë Investim me Vlerë në Rritje\nFalë zhvillimeve strategjike të infrastrukturës në jug të Shqipërisë, si Tuneli i Llogarasë dhe Aeroporti Ndërkombëtar i Vlorës, Aria Residence përfaqëson jo vetëm një vend ideal për të jetuar apo pushuar, por edhe një investim me potencial të lartë për rritje të vlerës dhe të ardhura nga qiratë sezonale premium.\n\nAria Residence nuk është thjesht një apartament pranë detit – është një investim në cilësinë e jetesës dhe një mundësi për të qenë pjesë e një prej destinacioneve më ekskluzive të Mesdheut.",
        "saleCommissionRatePercent": "4",
        "reservationCommissionRatePercent": "2",
        "featuredOnHomepage": true,
        "featuredSortOrder": 1,
        "magazineTitle": "dsfasdf",
        "magazineDescription": "asdfsadfsadfasdfasdf",
        "socialLinks": [
            {
                "name": "123",
                "link": "https://asdasd.com"
            }
        ],
        "mainImageId": "6a4f94ae99511ee1e0efb77c"
    }
];
