import {registerRoomDisplayNames} from "@coreModule/websocket/roomRegistry";

export function registerPropertyManagementRoomContributions(): void {
    registerRoomDisplayNames({
        overview: "Overview",
        dashboard: "Dashboard",
        projects: "Projects",
        edifices: "Edifices",
        floors: "Floors",
        units: "Units",
        leads: "Leads",
        inspections: "Inspections",
        modificationRequests: "Modification requests",
        reservations: "Reservations",
        sales: "Sales",
        contractsHub: "Contracts hub",
        commissions: "Commissions",
        constructionUpdates: "Construction updates",
        snags: "Snags",
        milestones: "Milestones",
        scheduleTasks: "Schedule tasks",
        projectDocuments: "Project documents",
        permits: "Permits",
        rentalsHub: "Rentals hub",
        ownerPortal: "Owner portal",
        leases: "Leases",
        rentalPayments: "Rental payments",
        groupDashboard: "Group dashboard",
        agentReport: "Agent report",
        roi: "ROI",
        erpExport: "ERP export",
        unitCosts: "Unit costs",
        unitTypes_configurations: "Unit types configurations",
        unitTypeCategories_configurations: "Unit type categories configurations",
        constructors_configurations: "Constructors configurations",
        budgets: "Budgets",
        boqItems: "Boq Items",
        costclassifications: "Cost Classifications",
        estimateComparison: "Estimate Comparison",
        specifications: "Specifications",
        specificationitems: "Specification Items",
        tenders: "Tenders",
        tenderinvitations: "Tender Invitations",
        bids: "Bids",
        bidlines: "Bid Lines",
        bidComparison: "Bid Comparison",
        approvalworkflows: "Approval Workflows",
        approvalrequests: "Approval Requests",
        contractorinvoices: "Contractor Invoices",
        incominginvoices: "Incoming Invoices",
        costControl: "Cost Control",
        liquidityplans: "Liquidity Plans",
        liquiditylines: "Liquidity Lines",
        feecalculations: "Fee Calculations",
        planmarkups: "Plan Markups",
        cockpit: "Cockpit",
        assets: "Assets",
        maintenanceplans: "Maintenance Plans",
        maintenanceworkorders: "Maintenance Work Orders",
        bimmodels: "BIM Models",
        bimquantities: "BIM Quantities",
        analytics: "Analytics",
        costCommitments: "Cost Commitments",
        workPackages: "Work Packages",
        constructionContracts: "Construction Contracts",
        progressClaims: "Progress Claims",
        rfis: "Rfis",
        submittals: "Submittals",
        variationOrders: "Variation Orders",
        landParcels: "Land Parcels",
        feasibilityStudies: "Feasibility Studies",
        siteDiaries: "Site Diaries",
        safetyIncidents: "Safety Incidents",
        warranties: "Warranties",
        handoverPackages: "Handover Packages",
        commissioningRecords: "Commissioning Records",
        designStages: "Design Stages",
        inspectionChecklistTemplates: "Inspection Checklist Templates",
        consultantAppointments: "Consultant Appointments",
        milestones: "Milestones",
        scheduleTasks: "Schedule Tasks",
    });
}
